title: The Stupid Hackathon Thailand
description: >-
  สร้างสิ่งของเพี้ยน ๆ ที่ไม่มีใครต้องการ และทำไอเดียบ้า ๆ บอ ๆ ให้กลายเป็นจริง ! งาน Hackathon แบบกี๊ค ๆ ที่ไม่จำกัดไอเดีย ไม่เน้นฝั่งธุรกิจ แต่เน้นความสนุกสำหรับนักพัฒนาแบบเพียว ๆ !!
host: 0.0.0.0
